/**
 * Writes `submodules/PaiUI/Sources/PaiSecrets.swift` (gitignored) from the box the `pai` CLI
 * already knows (`~/.config/pai/box.json`), so the app ships with its server and token built in.
 */
import { homedir } from "node:os";

const root = new URL("..", import.meta.url).pathname;
const boxFile = `${homedir()}/.config/pai/box.json`;

export async function writeSecrets() {
  const box = Bun.file(boxFile);
  if (!(await box.exists())) throw new Error(`${boxFile} is missing: run any \`pai\` command once so it learns the box`);
  const { url, token } = (await box.json()) as { url: string; token: string };
  if (!url || !token) throw new Error(`${boxFile} has no url or token`);
  const info = await fetch(`${url}/m/telegram/info`, { headers: { Authorization: `Bearer ${token}` } });
  if (!info.ok) throw new Error(`${url}/m/telegram/info answered HTTP ${info.status}: is the telegram module running?`);
  const { botUsername } = (await info.json()) as { botUsername: string };
  if (!botUsername) throw new Error("the box does not know its bot username yet");
  await Bun.write(
    `${root}submodules/PaiUI/Sources/PaiSecrets.swift`,
    `// Generated by scripts/secrets.ts from ~/.config/pai/box.json and the box. Not committed.\npublic enum PaiSecrets {\n    public static let baseURL = ${JSON.stringify(url)}\n    public static let token = ${JSON.stringify(token)}\n    public static let botUsername = ${JSON.stringify(botUsername)}\n}\n`,
  );
}

if (import.meta.main) await writeSecrets();
