/**
 * Writes `submodules/PaiUI/Sources/PaiSecrets.swift` (gitignored) so the app ships with its server,
 * token and bot name built in. On a developer's Mac they come from the box the `pai` CLI already
 * knows (`~/.config/pai/box.json`); on CI, where there is no box file, from `PAI_BOX_URL`,
 * `PAI_BOX_TOKEN` and `PAI_BOT_USERNAME`.
 */
import { homedir } from "node:os";
import { secretsPath } from "./repo.ts";

const boxFile = `${homedir()}/.config/pai/box.json`;

async function server(): Promise<{ url: string; token: string }> {
  const { PAI_BOX_URL, PAI_BOX_TOKEN } = process.env;
  if (PAI_BOX_URL && PAI_BOX_TOKEN) return { url: PAI_BOX_URL, token: PAI_BOX_TOKEN };
  const box = Bun.file(boxFile);
  if (!(await box.exists())) throw new Error(`${boxFile} is missing: run any \`pai\` command once so it learns the box, or set PAI_BOX_URL and PAI_BOX_TOKEN`);
  const { url, token } = (await box.json()) as { url?: string; token?: string };
  if (!url || !token) throw new Error(`${boxFile} has no url or token`);
  return { url, token };
}

/** The box knows which bot it talks through. */
export async function fetchBotUsername(url: string, token: string): Promise<string> {
  const info = await fetch(`${url}/m/telegram/info`, { headers: { Authorization: `Bearer ${token}` } });
  if (!info.ok) throw new Error(`${url}/m/telegram/info answered HTTP ${info.status}: is the telegram module running?`);
  const { botUsername } = (await info.json()) as { botUsername?: string };
  if (!botUsername) throw new Error("the box does not know its bot username yet");
  return botUsername;
}

export async function writeSecrets() {
  const { url, token } = await server();
  // `PAI_BOT_USERNAME` saves CI a round trip to a box it may not reach.
  const bot = process.env.PAI_BOT_USERNAME ?? (await fetchBotUsername(url, token));
  await Bun.write(
    secretsPath,
    `// Generated by scripts/secrets.ts from the box. Not committed.\npublic enum PaiSecrets {\n    public static let baseURL = ${JSON.stringify(url)}\n    public static let token = ${JSON.stringify(token)}\n    public static let botUsername = ${JSON.stringify(bot)}\n}\n`,
  );
}

if (import.meta.main) await writeSecrets();
